version: '3'
services:
  babylist:
    build: .
    image: 496096642801.dkr.ecr.us-west-2.amazonaws.com/fbctf-2019:babylist
    read_only: true
    volumes:
     - logs:/var/log
    ports:
     - "2301:2301"

volumes:
  logs: